version: "3"
# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

services:
  pfcp-agent:
    image: ${PFCP_AGENT_IMAGE}
    hostname: pfcp-agent
    container_name: pfcp-agent
    tty: true
    stdin_open: true
    volumes:
      - ./tmp:/tmp
      - ./config/pfcp-agent/config.json:/config.json
    entrypoint: "/bin/pfcpiface"
    command: [ "-config", "/config.json"]
    working_dir: /bin/
    expose:
      - 8805
  mock-smf:
    image: ${PFCPSIM_IMAGE}
    hostname: mock-smf
    container_name: mock-smf
    tty: true
    volumes:
      - ./tmp:/tmp
      - ./topo:/topo
      - ./bin:/up4/bin
  p4rt:
    build:
      context: ./topo
      dockerfile: Dockerfile.p4rt
    hostname: p4rt
    container_name: p4rt
    tty: true
    stdin_open: true
    volumes:
      - ./tmp:/tmp
      - ../p4src/build/:/p4c-out/
      - ./bin:/up4/bin
    entrypoint: "/bin/bash"
  mininet:
    build:
      context: ./topo
      dockerfile: Dockerfile.mn
      args:
        - DBUF_IMAGE=${DBUF_IMAGE}
        - MN_STRATUM_IMAGE=${MN_STRATUM_IMAGE}
    hostname: mininet
    container_name: mininet
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: "/topo/mn-entrypoint.sh"
    volumes:
      - ./tmp:/tmp
      - ./topo:/topo
      - ./bin:/up4/bin
      - ./tmp/pcaps:/pcaps
    expose:
      - 50001 # leaf1
      - 50002 # leaf2
      - 50003 # spine1
      - 50004 # spine2
    environment:
      - PARALLEL_LINKS=${PARALLEL_LINKS}
      - MN_SCRIPT=${MN_SCRIPT}
  onos1:
    # Tost image comes with latest trellis apps
    image: ${ONOS_IMAGE}
    hostname: onos1
    container_name: onos1
    ports:
      - "8181:8181" # HTTP
      - "8101:8101" # SSH (CLI)
      - "51001:51001" # UP4 app's P4Runtime server
      - "5005:5005" # Java debugger
    volumes:
      - ./config/onos/onos1.json:/root/onos/config/cluster.json
      - ./tmp/onos1:/root/onos/apache-karaf-4.2.14/data/tmp
    env_file:
      - ${STC_ENV_FILE} # Includes ONOS_APPS
    entrypoint: "./bin/onos-service"
    command: [ "debug" ]
  onos2:
    image: ${ONOS_IMAGE}
    hostname: onos2
    container_name: onos2
    ports:
      - "8182:8181"
      - "8102:8101"
      - "5006:5005"
    expose:
      # Same UP4's P4Runtime server as onos1, but no need to publish to the host machine (onos1 is
      # published for development/debugging). For other onos instances it will only be accessible to
      # linked services.
      - 51001
    volumes:
      - ./config/onos/onos2.json:/root/onos/config/cluster.json
      - ./tmp/onos2:/root/onos/apache-karaf-4.2.14/data/tmp
    env_file:
      - ${STC_ENV_FILE}
    entrypoint: "./bin/onos-service"
    command: [ "debug" ]
  onos3:
    image: ${ONOS_IMAGE}
    hostname: onos3
    container_name: onos3
    ports:
      - "8183:8181"
      - "8103:8101"
      - "5007:5005"
    expose:
      - 51001
    volumes:
      - ./config/onos/onos3.json:/root/onos/config/cluster.json
      - ./tmp/onos3:/root/onos/apache-karaf-4.2.14/data/tmp
    env_file:
      - ${STC_ENV_FILE}
    entrypoint: "./bin/onos-service"
    command: [ "debug" ]
  atomix1:
    image: ${ATOMIX_IMAGE}
    container_name: atomix1
    hostname: atomix1
    expose:
      - 5678
      - 5679
    volumes:
      - ./config/atomix/atomix1.conf:/opt/atomix/conf/atomix.conf
  atomix2:
    image: ${ATOMIX_IMAGE}
    container_name: atomix2
    hostname: atomix2
    expose:
      - 5678
      - 5679
    volumes:
      - ./config/atomix/atomix2.conf:/opt/atomix/conf/atomix.conf
  atomix3:
    image: ${ATOMIX_IMAGE}
    container_name: atomix3
    hostname: atomix3
    expose:
      - 5678
      - 5679
    volumes:
      - ./config/atomix/atomix3.conf:/opt/atomix/conf/atomix.conf
