# SPDX-FileCopyrightText: 2020 Open Networking Foundation <info@opennetworking.org>
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

ARG SCAPY_BASE_IMAGE

FROM $SCAPY_BASE_IMAGE
RUN apt-get update && apt-get install -y git net-tools tcpdump vim iputils-ping screen
RUN pip3 install ifcfg git+https://github.com/secdev/scapy
