# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0
#
version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Docker login
          command: docker login registry.aetherproject.org -u $AETHER_DOCKER_USER -p $AETHER_DOCKER_PASSWORD
      - run:
          name: Dependencies
          command: |
            make deps
            cd app && make deps
            cd ../scenarios && make deps
      - run:
          name: Build P4 program
          command: make build
      - run:
          name: Check if P4Info is up-to-date
          command: |
            modified=$(git status --porcelain)
            if [ -n "$modified" ]; then
              echo "The following P4 build artifacts do not correspond to the expected ones,"
              echo "please run the build locally and commit any changes to these files:"
              echo "$modified"
              exit 1
            fi
      - run:
          name: Run PTF tests
          command: make check
      - run:
          name: Build ONOS app
          command: cd app && make build-ci
      - run:
          name: Smoke test
          command: |
            cd scenarios
            # Avoid Docker setting root permissions on tmp
            mkdir -p ./tmp
            make smoke.xml
      - run:
          name: Dump ONOS logs
          command: cd scenarios && docker-compose logs onos1 > tmp/onos.log
          when: on_fail
      - store_artifacts:
          path: scenarios/tmp
      - run:
          name: Upload coverage
          command: cd app && bash <(curl -s https://codecov.io/bash)
          environment:
            CODECOV_TOKEN: 26252f52-8c2d-4cfd-bd2f-ec00a71d2942

workflows:
  main:
    jobs:
      - build-and-test
