version: 2.1
jobs:
  p4-build-and-test:
    machine: true
    steps:
      - checkout
      - run: make deps build check
  app-build-and-test:
    machine: true
    steps:
      - checkout
      - run:
          name: Build app
          command: cd app && make deps build-ci
      - run:
          name: App integration test
          command: cd app && make check-slow
      - run:
          name: Upload coverage
          command: cd app && bash <(curl -s https://codecov.io/bash)
          environment:
            CODECOV_TOKEN: 26252f52-8c2d-4cfd-bd2f-ec00a71d2942

workflows:
  main:
    jobs:
      - p4-build-and-test
      - app-build-and-test
