version: 2.1
jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: echo ${AETHER_DOCKER_PASSWORD} | docker login registry.aetherproject.org --username ${AETHER_DOCKER_USER}
      - run:
          name: Dependencies
          command: make deps && cd app && make deps
      - run:
          name: Build P4 program
          command: make build
      - run:
          name: Check if P4Info is up-to-date
          command: |
            modified=$(git status --porcelain)
            if [ -n "$modified" ]; then
              echo "The following P4 build artifacts do not correspond to the expected ones,"
              echo "please run the build locally and commit any changes to these files:"
              echo "$modified"
              exit 1
            fi
      - run:
          name: Run PTF tests
          command: make check
      - run:
          name: Build ONOS app
          command: cd app && make build-ci
      - run:
          name: App integration test
          command: cd app && make check-slow
      # FIXME: Should upload as build artifacts instead of printing on screen
      - run:
          name: Print ONOS logs
          command: cd app && docker logs onos
          when: on_fail
      - run:
          name: Upload coverage
          command: cd app && bash <(curl -s https://codecov.io/bash)
          environment:
            CODECOV_TOKEN: 26252f52-8c2d-4cfd-bd2f-ec00a71d2942

workflows:
  main:
    jobs:
      - build-and-test
