version: 2.1

jobs:
  p4-build-and-test:
    machine: true
    steps:
      - checkout
      - run: make deps build check
  app-build-and-test:
    machine: true
    steps:
      - checkout
      - run: cd app && make deps build check-slow

workflows:
  main:
    jobs:
      - p4-build-and-test
      - app-build-and-test
