version: 2.1

jobs:
  p4-build-and-test:
    machine: true
    steps:
      - checkout
      - run: make deps build check
  app-build-and-test:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: cd app && mvn install

workflows:
  main:
    jobs:
      - p4-build-and-test
      - app-build-and-test
