version: 2.1
jobs:
  p4-build-and-test:
    machine: true
    steps:
      - checkout
      - run:
          name: Dependencies
          command: make deps
      - run:
          name: Build P4 program
          command: make build
      - run:
          name: Check if P4Info is up-to-date
          command: |
            modified=$(git status --porcelain)
            if [ -n "$modified" ]; then
              echo "The following P4 build artifacts do not correspond to the expected ones,"
              echo "please run the build locally and commit any changes to these files:"
              echo "$modified"
              exit 1
            fi
      - run:
          name: Run PTF tests
          command: make check
      - run: make deps build check
  app-build-and-test:
    machine: true
    steps:
      - checkout
      - run:
          name: Build app
          command: cd app && make deps build-ci
      - run:
          name: App integration test
          command: cd app && make check-slow
      - run:
          name: Print ONOS logs
          command: cd app && docker logs onos
          when: on_fail
      - run:
          name: Upload coverage
          command: cd app && bash <(curl -s https://codecov.io/bash)
          environment:
            CODECOV_TOKEN: 26252f52-8c2d-4cfd-bd2f-ec00a71d2942

workflows:
  main:
    jobs:
      - p4-build-and-test
      - app-build-and-test
