/*
 * SPDX-License-Identifier: LicenseRef-ONF-Member-1.0
 * SPDX-FileCopyrightText: {year}-present Open Networking Foundation <info@opennetworking.org>
 */

package org.omecproject.up4;

import com.google.common.annotations.Beta;
import org.onlab.packet.Ip4Address;

/**
 * Information about an event generated by Up4Service.
 */
@Beta
public final class Up4EventSubject {

    private final Ip4Address ueAddress;

    public Up4EventSubject(Ip4Address ueAddress) {
        this.ueAddress = ueAddress;
    }

    /**
     * UE Ipv4 address associated to this event, or null if not meaningful for the event.
     * @return Ue IPv4 address
     */
    public Ip4Address ueAddress() {
        return ueAddress;
    }
}
