/*
 * SPDX-License-Identifier: LicenseRef-ONF-Member-1.0
 * SPDX-FileCopyrightText: {year}-present Open Networking Foundation <info@opennetworking.org>
 */

package org.omecproject.up4;

import com.google.common.annotations.Beta;
import org.onlab.util.ImmutableByteSequence;

/**
 * Information about an event generated by Up4Service.
 */
@Beta
public final class Up4EventSubject {

    private final ImmutableByteSequence fseid;

    public Up4EventSubject(ImmutableByteSequence fseid) {
        this.fseid = fseid;
    }

    /**
     * F-SEID associated to this event, or null if not meaningful for the event.
     * @return F-SEID
     */
    // FIXME: create a proper class for F-SEID with UPF IP Address and SEID
    public ImmutableByteSequence fseid() {
        return fseid;
    }
}
