version: "3"
# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

services:
  pfcp:
    #image: registry.central.aetherproject.net/pfcp-upf-2.0-bad
    #image: upf-epc-pfcpiface:0.2.0-dev
    image: badhri85/upf-epc-pfcpiface:0.1.2-dev
    hostname: pfcp
    container_name: pfcp
    tty: true
    stdin_open: true
    ports:
      - "8805:8805" # SSH (CLI)
    volumes:
      - ./tmp:/tmp
      - ./util:/util/
    links:
      - mininet
      - onos
    entrypoint: "/util/pfcp-entry.sh"
    working_dir: /bin/
    depends_on:
      - mininet
  scapy:
    build:
      context: ./pfcp-scapy
    hostname: scapy
    container_name: scapy
    tty: true
    stdin_open: true
    ports:
      - "8282:8282" # HTTP
      - "8202:8202" # SSH (CLI)
    volumes:
      - ./tmp:/tmp
      - ./util:/util/
    links:
      - pfcp
    entrypoint: "/bin/sh"
    depends_on:
      - pfcp
      - mininet
  mininet:
    build:
      context: ./util
      dockerfile: Dockerfile.mn
    hostname: mininet
    container_name: mininet
    privileged: true
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./tmp:/tmp
      - ./util:/util
      - ./tmp/pcaps:/pcaps
    ports:
      - "50001:50001"
      - "50002:50002"
      - "50003:50003"
      - "50004:50004"
      - "10000:10000" # dbuf service
    entrypoint: "/util/mininet-entry.sh"
  onos:
    image: onosproject/onos:2.2-latest
    hostname: onos
    container_name: onos
    ports:
      - "8181:8181" # HTTP
      - "8101:8101" # SSH (CLI)
      - "51001:51001" # the UP4 app's gRPC server port
      - "5005:5005" # Java debugger
    volumes:
      - ./tmp/onos:/root/onos/apache-karaf-4.2.8/data/tmp
      - ./tmp/pcaps:/pcaps
    environment:
      - ONOS_APPS=gui2,drivers.bmv2,lldpprovider,hostprovider,pipelines.fabric,segmentrouting,netcfghostprovider,protocols.grpc
      - JAVA_DEBUG_PORT=0.0.0.0:5005
    entrypoint: "./bin/onos-service"
    command: ["debug"]
    links:
      - mininet
