#!/bin/bash
# SPDX-FileCopyrightText: 2020 Open Networking Foundation <info@opennetworking.org>
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

docker run --rm -it --network host bocon/gnmi-cli:latest $@
