version: "2"

services:
  mininet:
    image: opennetworking/ngsdn-tutorial:stratum_bmv2 
    hostname: mininet
    container_name: mininet
    privileged: true
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./tmp:/tmp
      - ./util:/util
    ports:
      - "50001:50001"
      - "50002:50002"
      - "50003:50003"
      - "50004:50004"
    # NGSDN_TOPO_PY is a Python-based Mininet script defining the topology. Its
    # value is passed to docker-compose as an environment variable, defined in
    # the Makefile.
    entrypoint: "/util/${NGSDN_TOPO_PY}"
  pfcp:
    image: ngic-dp:test-2.0-debug
    hostname: pfcp
    container_name: pfcp
    tty: true
    stdin_open: true
    ports:
      - "8101:8101" # SSH (CLI)
      - "8805:8805" # SSH (CLI)
    volumes:
      - ./tmp:/tmp
    links:
      - mininet
    entrypoint: "/bin/sh"
    depends_on:
      - mininet
  scapy:
    image: pfcp-tool:0.1.0
    hostname: scapy
    container_name: scapy
    tty: true
    stdin_open: true
    ports:
      - "8282:8282" # HTTP
      - "8202:8202" # SSH (CLI)
    volumes:
      - ./tmp:/tmp
    links:
      - pfcp
    entrypoint: "/bin/sh"
    depends_on:
      - pfcp
      - mininet
