# SPDX-FileCopyrightText: 2020 Open Networking Foundation <info@opennetworking.org>
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

# Regular mn-stratum with dbuf binary.

FROM registry.aetherproject.org/tost/dbuf as dbuf
RUN mkdir /output
RUN cp $(which dbuf) /output/dbuf

FROM opennetworking/mn-stratum:lates
COPY --from=dbuf /output/dbuf /usr/local/bin
