#!/bin/bash
# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

IMG_NAME="pfcp-client"
LOG_FILE="tmp/pfcp-messenger-screen.log"
AGENT_NAME="pfcp-agent"
if [ $1 = "start" ]; then
    echo "" > $LOG_FILE
    docker-compose exec -d $IMG_NAME screen -L -Logfile /$LOG_FILE -m -S Messenger /util/pfcp-messenger.py $AGENT_NAME 
    docker-compose exec $IMG_NAME screen -S Messenger -X colon "logfile flush 0^M"
elif [ $1 = "kill" ]; then
    docker-compose exec -d $IMG_NAME screen -X -S Messenger quit
elif [ $1 = "check" ]; then
    tail -n 1 $LOG_FILE \
        | grep "Enter your selection" || exit 1  # Check it started
    docker-compose exec $IMG_NAME screen -ls \
        | grep "Messenger" \
        | grep "Attached" || exit 1  # Check its alive
    exit 0
else
    ARGS="$@"  # an intermediate variable is needed for some reason 
    docker-compose exec -d $IMG_NAME screen -S Messenger -p 0 -X stuff "${ARGS}"
fi
