# SPDX-FileCopyrightText: 2020 Open Networking Foundation <info@opennetworking.org>
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

# Regular mn-stratum with dbuf binary.

FROM registry.aetherproject.org/tost/dbuf as dbuf
RUN mkdir /output
RUN cp $(which dbuf) /output/dbuf

# Why are we not using opennetworking/mn-stratum:latest?
FROM opennetworking/ngsdn-tutorial:stratum_bmv2
COPY --from=dbuf /output/dbuf /usr/local/bin
